/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import sys.crudtable;

/**
 *
 * @author Acer
 */
public class Framenilai extends javax.swing.JFrame {
    
String judulkolom[] = {"npm", "nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
int lebarkolom[] = {150, 300, 200, 100, 100, 100};
String SQL = "SELECT *FROM khs";

    /**
     * Creates new form Framenilai
     */
    private crudtable myObject;
    public Framenilai() {
        initComponents();
        myObject = new crudtable();
        myObject.settingJudulTabel(tablenilai, judulkolom);
        myObject.settingLebarKolom(tablenilai, lebarkolom);
        myObject.tampilTabel(tablenilai, SQL, judulkolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnpm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtips1 = new javax.swing.JTextField();
        txtips2 = new javax.swing.JTextField();
        txtips3 = new javax.swing.JTextField();
        txtips4 = new javax.swing.JTextField();
        txtips5 = new javax.swing.JTextField();
        txtips6 = new javax.swing.JTextField();
        txtips7 = new javax.swing.JTextField();
        txtipk = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablenilai = new javax.swing.JTable();
        btncetak = new javax.swing.JButton();
        btnbersih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("npm");

        jLabel2.setText("nama");

        jLabel3.setText("ips1");

        jLabel4.setText("ips2");

        jLabel5.setText("ips3");

        jLabel6.setText("ips4");

        jLabel7.setText("ips5");

        jLabel8.setText("ips6");

        jLabel9.setText("ips7");

        jLabel10.setText("ipk");

        txtips1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtips1ActionPerformed(evt);
            }
        });

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        tablenilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablenilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablenilai);

        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        btnbersih.setText("BERSIH");
        btnbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnpm, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtips6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtips5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtips4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtips2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtips1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtips3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtips7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtipk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnbersih)
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnubah)
                        .addGap(39, 39, 39)
                        .addComponent(btnhapus)
                        .addGap(40, 40, 40)
                        .addComponent(btncetak))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtipk, txtips1, txtips2, txtips3, txtips4, txtips5, txtips6, txtips7, txtnama, txtnpm});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhapus)
                            .addComponent(btncetak)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnubah)
                                .addComponent(btnsimpan)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtnpm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtips1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtips2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtips3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtips4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtips5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtips6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtips7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtipk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(btnbersih)
                        .addGap(0, 79, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtips1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtips1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtips1ActionPerformed

    private void tablenilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenilaiMouseClicked
        // TODO add your handling code here:
    int selectedRow = tablenilai.getSelectedRow();
        if (selectedRow != -1) {
            txtnpm.setText(tablenilai.getValueAt(selectedRow, 0).toString());
            txtnama.setText(tablenilai.getValueAt(selectedRow, 1).toString());
            txtips1.setText(tablenilai.getValueAt(selectedRow, 2).toString());
            txtips2.setText(tablenilai.getValueAt(selectedRow, 3).toString());
            txtips3.setText(tablenilai.getValueAt(selectedRow, 4).toString());
            txtips4.setText(tablenilai.getValueAt(selectedRow, 5).toString());
            txtips5.setText(tablenilai.getValueAt(selectedRow, 6).toString());
            txtips6.setText(tablenilai.getValueAt(selectedRow, 7).toString());
            txtips7.setText(tablenilai.getValueAt(selectedRow, 8).toString());
            txtipk.setText(tablenilai.getValueAt(selectedRow, 9).toString());
            myObject.tampilTabel(tablenilai, SQL, judulkolom);
        }
    }//GEN-LAST:event_tablenilaiMouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
       // TODO add your handling code here:
    // TODO add your handling code here:
        try {
        // Ambil data dari form
        String npm = txtnpm.getText().trim();
        String nama = txtnama.getText().trim();
        double ips1 = Double.parseDouble(txtips1.getText().trim());
        double ips2 = Double.parseDouble(txtips2.getText().trim());
        double ips3 = Double.parseDouble(txtips3.getText().trim());
        double ips4 = Double.parseDouble(txtips4.getText().trim());
        double ips5 = Double.parseDouble(txtips5.getText().trim());
        double ips6 = Double.parseDouble(txtips6.getText().trim());
        double ips7 = Double.parseDouble(txtips7.getText().trim());

        // Hitung IPK (rata-rata dari IPS1 hingga IPS7)
        double ipk = (ips1 + ips2 + ips3 + ips4 + ips5 + ips6 + ips7) / 7;

        // Format IPK menjadi 2 angka di belakang koma (opsional)
        ipk = Math.round(ipk * 100.0) / 100.0;

        // Simpan data ke database menggunakan fungsi CRUD dinamis
        String[] fields = {"npm", "nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
        String[] values = {
            npm,
            nama,
            String.valueOf(ips1),
            String.valueOf(ips2),
            String.valueOf(ips3),
            String.valueOf(ips4),
            String.valueOf(ips5),
            String.valueOf(ips6),
            String.valueOf(ips7),
            String.valueOf(ipk)
        };
        myObject.SimpanDinamis("khs", fields, values);

        // Tampilkan IPK ke text field atau area lain di GUI
        txtipk.setText(String.valueOf(ipk));

        // Berikan notifikasi kepada pengguna
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan! IPK: " + ipk);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap masukkan nilai IPS dengan format angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        myObject.tampilTabel(tablenilai, SQL, judulkolom);
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
    // TODO add your handling code here:
        try {
        // Ambil data dari form
        String npm = txtnpm.getText().trim();
        String nama = txtnama.getText().trim();
        double ips1 = Double.parseDouble(txtips1.getText().trim());
        double ips2 = Double.parseDouble(txtips2.getText().trim());
        double ips3 = Double.parseDouble(txtips3.getText().trim());
        double ips4 = Double.parseDouble(txtips4.getText().trim());
        double ips5 = Double.parseDouble(txtips5.getText().trim());
        double ips6 = Double.parseDouble(txtips6.getText().trim());
        double ips7 = Double.parseDouble(txtips7.getText().trim());

        // Hitung ulang IPK (rata-rata dari IPS1 hingga IPS7)
        double ipk = (ips1 + ips2 + ips3 + ips4 + ips5 + ips6 + ips7) / 7;

        // Format IPK menjadi 2 angka di belakang koma (opsional)
        ipk = Math.round(ipk * 100.0) / 100.0;

        // Data yang akan diupdate
        String[] fields = {"nama", "ips1", "ips2", "ips3", "ips4", "ips5", "ips6", "ips7", "ipk"};
        String[] values = {
            nama,
            String.valueOf(ips1),
            String.valueOf(ips2),
            String.valueOf(ips3),
            String.valueOf(ips4),
            String.valueOf(ips5),
            String.valueOf(ips6),
            String.valueOf(ips7),
            String.valueOf(ipk)
        };

        // Update data menggunakan fungsi CRUD dinamis
        String[] isiPrimary = {"npm"}; 
            myObject.UbahDinamis("khs", "npm", txtnpm.getText(), fields, values);

        // Tampilkan kembali data ke tabel
        myObject.tampilTabel(tablenilai, SQL, judulkolom);
        txtipk.setText(String.valueOf(ipk));

        // Berikan notifikasi kepada pengguna
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harap masukkan nilai IPS dengan format angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
    try {
            String primaryKey = "npm";
            String primaryValue = txtnpm.getText();
            
            txtnpm.setText("");
            txtnama.setText("");
            txtips1.setText("");
            txtips2.setText("");
            txtips3.setText("");
            txtips4.setText("");
            txtips5.setText("");
            txtips6.setText("");
            txtips7.setText("");
            txtipk.setText("");
            myObject.HapusDinamis("nilai", primaryKey, primaryValue);
            myObject.tampilTabel(tablenilai, SQL, judulkolom);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
    try {
            String laporanfile = "src/laporan/laporan.jrxml";
            String SQL = "SELECT * From khs";
            
            myObject.tampilLaporan(laporanfile, SQL);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btncetakActionPerformed

    private void btnbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihActionPerformed
        // TODO add your handling code here:
    try {
            String primaryKey = "npm";
            String primaryValue = txtnpm.getText();
            
            txtnpm.setText("");
            txtnama.setText("");
            txtips1.setText("");
            txtips2.setText("");
            txtips3.setText("");
            txtips4.setText("");
            txtips5.setText("");
            txtips6.setText("");
            txtips7.setText("");
            txtipk.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnbersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Framenilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Framenilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Framenilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Framenilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framenilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersih;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablenilai;
    private javax.swing.JTextField txtipk;
    private javax.swing.JTextField txtips1;
    private javax.swing.JTextField txtips2;
    private javax.swing.JTextField txtips3;
    private javax.swing.JTextField txtips4;
    private javax.swing.JTextField txtips5;
    private javax.swing.JTextField txtips6;
    private javax.swing.JTextField txtips7;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnpm;
    // End of variables declaration//GEN-END:variables
}
